### ISSUE TITLE
Uncaught (in promise) Error: ws does not work in the browser. Browser clients must use the native WebSocket object

### ISSUE THREAD

**Issue by ChristianOConnor** [LIT-Protocol/lit-js-sdk#35]
I get this error when trying to run an app with Vite:  
```
DevTools failed to load source map: Could not load content for chrome-extension://<random looking string here>/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
browser-external:buffer:9 Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.
get @ browser-external:buffer:9
(anonymous) @ bn.js:56
node_modules/bn.js/lib/bn.js @ bn.js:3547
__require2 @ chunk-IKJM6GHQ.js?v=8cf5de14:18
node_modules/@ethersproject/bignumber/lib.esm/bignumber.js @ bignumber.ts:11
__init @ chunk-IKJM6GHQ.js?v=8cf5de14:15
node_modules/@ethersproject/bignumber/lib.esm/index.js @ index.ts:1
__init @ chunk-IKJM6GHQ.js?v=8cf5de14:15
node_modules/@ethersproject/units/lib.esm/index.js @ index.ts:4
__init @ chunk-IKJM6GHQ.js?v=8cf5de14:15
node_modules/lit-js-sdk/build/index.js @ index.js:18
__require2 @ chunk-IKJM6GHQ.js?v=8cf5de14:18
(anonymous) @ browser.js:19
browser-external:buffer:9 Module "buffer" has been externalized for browser compatibility. Cannot access "buffer.Buffer" in client code.
get @ browser-external:buffer:9
(anonymous) @ bn.js:53
node_modules/@walletconnect/utils/node_modules/bn.js/lib/bn.js @ bn.js:3427
__require2 @ chunk-IKJM6GHQ.js?v=8cf5de14:18
node_modules/@walletconnect/utils/dist/esm/encoding.js @ encoding.ts:1
__init @ chunk-IKJM6GHQ.js?v=8cf5de14:15
node_modules/@walletconnect/utils/dist/esm/index.js @ index.ts:4
__init @ chunk-IKJM6GHQ.js?v=8cf5de14:15
node_modules/@walletconnect/ethereum-provider/dist/esm/index.js @ index.ts:5
__init @ chunk-IKJM6GHQ.js?v=8cf5de14:15
node_modules/lit-js-sdk/build/index.js @ index.js:18
__require2 @ chunk-IKJM6GHQ.js?v=8cf5de14:18
(anonymous) @ browser.js:19
frameComms.js:4 calling listenForChildFrameMessages from http://127.0.0.1:5173
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7370/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7370/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7371/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7371/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7372/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7372/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7373/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7373/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7374/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7374/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7375/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7375/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7376/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7376/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7377/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7377/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7378/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7378/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] handshakeWithSgx https://node2.litgateway.com:7379/web/handshake
utils.js:35 [Lit-JS-SDK] sendCommandToNode with url https://node2.litgateway.com:7379/web/handshake and data {clientPublicKey: 'test'}
utils.js:35 [Lit-JS-SDK] lit is ready
utils.js:35 [Lit-JS-SDK] getting provider via lit connect modal
browser.js:4 Uncaught (in promise) Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new module.exports (browser.js:4:9)
    at SocketTransport._socketCreate (index.ts:140:24)
    at SocketTransport.open (index.ts:98:10)
    at WalletConnect._initTransport (index.ts:1117:21)
    at new Connector (index.ts:160:10)
    at new WalletConnect (index.ts:7:5)
    at SignerConnection.register (index.ts:119:65)
    at new SignerConnection (index.ts:31:20)
    at new WalletConnectProvider (index.ts:18:39)
    at Object.walletconnect (providerMethods.js:24:12)
```  

I'm using React and Vite. This is how `lit-js-sdk` is called:  
litProtocolFunctions.ts:  
```
//@ts-ignore
import LitJsSdk from 'lit-js-sdk';
import { baseUrlConf } from './config';

export function disconnectLit() {
    LitJsSdk.disconnectWeb3();
    return 'lit-auth';
}

export async function connectLit(uuidSpec: string) {

    const resourceId = {
        baseUrl: "http://" + baseUrlConf + ":3000",
        path: '/protected',
        orgId: "",
        role: "",
        extraData: uuidSpec
    }

    const chain = 'mumbai'
    const accessControlConditions = [
        {
            contractAddress: '<NFT CONTRACT ADDRESS>',
            standardContractType: 'ERC721',
            chain: chain,
            method: 'balanceOf',
            parameters: [
                ':userAddress'
            ],
            returnValueTest: {
                comparator: '>',
                value: '0'
            }
        },
    ]

    const client = new LitJsSdk.LitNodeClient({ alertWhenUnauthorized: false });
    //@ts-ignore
    await client.connect();
    const authSig = await LitJsSdk.checkAndSignAuthMessage({ chain });

    //@ts-ignore
    await client.saveSigningCondition({ accessControlConditions, chain, authSig, resourceId })
    try {
        //@ts-ignore
        const litjwt = await client.getSignedToken({
            accessControlConditions, chain, authSig, resourceId: resourceId
        });
        return litjwt;
    } catch (err) {
        console.log('error: ', err);
        return 'no-token';
    }
}
```  

Idk why this is happening. This is a Vite app so it's static and uses React.

**Comment by GTC6244** [comment]
This is a problem with vite failing to bundle WalletConnect properly - which we use to help select a signer.   Given that the root issue is missing polyfills, it's possible that removing WalletConnect might expose other missing polyfills that aren't caught by vite, but this solution seems to fix everything, so we haven't delved any further.

packages to add (I yarn stuff, but whatever manager you want) >>>

```
yarn add @esbuild-plugins/node-globals-polyfill
yarn add @rollup/plugin-inject
yarn add rollup-plugin-polyfill-node

```

And here's the new vite.config.ts that includes these packages and instructs vite (or merge into your changes - I started with the default).   I assume you already found the "global" as well! ;-) 

```
import { defineConfig } from "vite";
import react from '@vitejs/plugin-react'
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
import inject from "@rollup/plugin-inject";
import nodePolyfills from "rollup-plugin-polyfill-node";

// https://vitejs.dev/config/
export default defineConfig({
  base: "./",
  // Node.js global to browser globalThis
  define: {
    global: "globalThis",
  },
  plugins: [
    react(),
    inject({
      util: "util/",
    }),
  ],
  build: {
    rollupOptions: {
      plugins: [nodePolyfills()],
    },
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
      ],
        },
  },
});
```

**Comment by ChristianOConnor** [comment]
Oh nice this got me a lot closer thanks! I'm getting this error now:  
```
Uncaught (in promise) TypeError: import_events.EventEmitter is not a constructor
    at new JsonRpcProvider2 (null:30989:23)
    at new WalletConnectProvider (null:43692:23)
    at Object.walletconnect (null:44098:14)
    at null:44131:36
    at Array.forEach (<anonymous>)
    at p3._filterListOfWallets (null:44126:12)
    at new p3 (null:44103:153)
    at ke (null:61404:18)
    at Ne (null:61302:32)
    at Object.dt [as checkAndSignAuthMessage] (null:62066:217)
```  

Btw I modified my vite.config.js file as much as I could to get it close to yours. I still needed to define my root directory as the src file in my project and the output directory of the build:  
vite.config.js:  
```
import { resolve } from 'path'
import { defineConfig } from "vite";
import react from '@vitejs/plugin-react';
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
import inject from "@rollup/plugin-inject";
import nodePolyfills from "rollup-plugin-polyfill-node";

const root = resolve(__dirname, 'src')
const outDir = resolve(__dirname, 'dist')

// https://vitejs.dev/config/
export default defineConfig({
  root,
  base: "./",
  // Node.js global to browser globalThis
  define: {
    global: "globalThis",
  },
  plugins: [
    react(),
    inject({
      util: "util/",
    }),
  ],
  build: {
    outDir,
    emptyOutDir: true,
    rollupOptions: {
      plugins: [nodePolyfills()],
      input: {
        main: resolve(root, 'index.html'),
        about: resolve(root, 'protected', 'index.html'),
      }
    },
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
      ],
        },
  },
});
```  

Am I getting closer? What am I doing wrong here?

**Comment by ChristianOConnor** [comment]
This and 1 more step worked! I did exactly what you said but I got `Uncaught (in promise) TypeError: import_events.EventEmitter is not a constructor`  

I found this post on Stackoverflow https://stackoverflow.com/a/69917090/13215988. I followed it and ran `npm i --save events` then `npm i --save-dev @types/events @types/node` and then it worked!
